[package]
name = "gif-to-ascii"
version = "0.1.0"
edition = "2026"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = { version = "0.24", default-features = false, features = ["gif", "jpeg", "png"] }
console_error_panic_hook = "0.1.7"